config/routes.rb
JavaSubmissionTester::Engine.routes.draw do
  get 'pages/:page', to: 'pages#show', as: 'pages'
end

app/controllers/java_submission_tester/pages_controller.rb
module JavaSubmissionTester
  class PagesController < ::ApplicationController
    layout "application"

    def show
      render action: params[:page]
    end
  end
end

app/views/java_submission_tester/pages/how_to_jar.html.slim
= stylesheet_link_tag 'java_submission_tester/help'
= javascript_include_tag 'java_submission_tester/image-zoom'

= content_for :title
  | Hilfe - Wie erstelle ich eine Jar-Datei - IntelliJ

h1.text-center
  | Wie erstelle ich eine Jar-Datei in IntelliJ?
ol
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/start.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        | Öffne das IntelliJ Projekt, für das eine Jar-Datei erstellt werden soll.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/file-menu.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Öffne das Menü
        em File > Project Structure
        | .

  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/project-structure-artifacts.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Navigiere zu dem Menü
        em> Artifacts
        | auf der linken Seite.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/project-structure-artifacts-add.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Öffne über das grüne + das Auswahl Menü für die Artifacts.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/artifacts-jar.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Wähle die Option
        em Jar > from module with dependencies
        |.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-artifact-dialog.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        | Bestätige das Erstellen des Artefaktes mit Standardeinstellungen.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-jar-content.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        | Öffne über das grüne + das Menü um zusätzliche Inhalte in die Jar-Datei zu packen.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-jar-content-dir.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Wähle die Option
        em Directory Content
        |.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/add-jar-content-dir-src.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Wähle in dem Pop-up, das sich geöffnet hat den Ordner aus, der die Java-Dateien enthält. Dies ist standardmäßig
          der Ordner
        em src
        ' . Wähle
        strong> NICHT
        ' den Ordner, der das Projekt enthält, sonst werden viele unnötige Dateien in die Jar-Datei gepackt. Danach
          bestätige die Auswahl und schließe das Pop-up.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/menu-build-artifacts.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Um die Jar-Datei zu bauen, navigiere zu
        em Build > Build Artifacts...
        | .
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/artifact-build.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' In dem Pop-up das sich geöffnet hat die Aktion
        em> Build
        ' auswählen.
  .row.space
    .col-sm-12.col-md-6
      = image_tag 'java_submission_tester/finish.png', class: 'zoomable'
    .col-sm-12.col-md-6
      li
        ' Herzlichen Glückwunsch. Die fertige Jar-Datei wird in dem Ordner
        em> out/artifacts/...
        ' abgelegt.

app/views/java_submission_tester/pages/student_help_io.html.slim
h1
  | Hilfe

h3
  | Allgemein

p
  ' IO-Aufgaben generieren für jede Person eine individuelle Eingabe, mit der eine Aufgabe gelöst werden soll.
  ' Das Ergebnis einer Aufgabe ist wieder ein Text, der von Dozentron automatisch bewertet wird.
  ' Zusätzlich zu dem Ergebnistext kann auch der Quellcode des Programms abgegeben werden, dass die Aufgabe gelöst hat.
  ' Dieses Programm wird von Dozentron
  strong> NICHT
  ' ausgeführt. Die Abgabe des Quellcodes ist nur für den Dozenten und die Tutoren, damit Sie sich ihre Ergebnisse noch
  ' einmal ansehen und von Hand bewerten können.

app/views/java_submission_tester/pages/student_help_submission.html.slim
= stylesheet_link_tag 'java_submission_tester/help'

= content_for :title
  | Java Tester Hilfe

.row
  h1
    | Hilfe

.col-sm-12: markdown:
  ## Was ist eine JAR?

  Eine JAR ist eine Java Archive Datei, ein spezielles Format, das Klassen und Interfaces, falls gewünscht auch komprimiert, im Zip-Vormat bündelt und diese leichter übertragbar macht.
  Außerdem ist der in JARs enthaltene Code direkt ausführbar.

  Wer sich näher zum Format und dessen Funktionalitäten informieren möchte, kann das unter anderem hier tun:

    * [Java ist auch nur eine Insel](http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_26_003.htm#mjf3bbdf106879ed579fef84173ca9be20)

    * [Java Documentation von Oracle](https://docs.oracle.com/javase/tutorial/deployment/jar/index.html)

  ## Wie erstelle ich eine Jar?

  [#{pages_path(:how_to_jar)}](#{image_tag 'java_submission_tester/IntelliJ_IDEA_Logo.svg'}) [IntelliJ](#{pages_path(:how_to_jar)})

  ## Was in die JAR rein muss (und was nicht)

  * In der JAR sollte, wie bereits in der Anleitung zum Erstellen einer JAR-Datei via IntelliJ beschrieben, alles was auch im src (source) Ordner des Projektes liegt enthalten sein. Also alle Klassen, Interfaces usw., die Ihr selbst geschrieben habt. Sollte für eine Abgabe mehr benötigt werden, wird dort explizit darauf hingewiesen.

  * Was nicht in die Abgabedatei gehört, sind unter anderem JUnit-Tests, da sonst die Software, die im Code nach Ähnlichkeiten (Plagiaten) such, anschlägt.

  ## Fehlermeldungen und Troubleshooting

  ### Die Fehlermeldungen

  * > Dateityp muss jar sein

  Diese Fehlermeldungen erklärt sich eigentlich von selbst.
  Die hochgeladene Datei muss die Dateiendung .jar haben, sonst funktioniert es nicht.
  Infomationen darüber, was eine JAR ist und Hilfe dazu, wie man mit IntelliJ eine JAR
   erstellt,  finden sich in der Anleitung [How to jar](#{pages_path(:how_to_jar)}).

  * > Abgabe kann nicht compiliert werden

  Diese Fehlermeldungen zeigt an, dass mit dem hochgeladenen Code etwas nicht stimmt.
  Ein Klick auf den Button **Details** zeigt an, welche Fehler der JUnit-Test geworfen hat
  und liefert Anhaltspunkte, wo nochmal geschaut werden sollte.
  *Cannot find symbol* kann zum Beispiel auf einen Schreibfehler im Namen von
  Klassen oder Variablen hindeuten, falls diese vorgegeben waren.

  * > Abgabe muss die Class Dateien enthalten

  Diese Fehlermeldungen ist ebenfalls recht eindeutig.
  Die hochgeladene JAR enthält keine .class-Dateien.
  JARs lassen sich zum Beispiel mit der Archivverwaltung öffnen, damit der Inhalt
  überprüft werden kann. Im zweifel kann im [Tutorial zu JARs](#{pages_path(:how_to_jar)})
  nochmal überprüft werden, ob beim Erstellen der Datei alle Schritte richtig gemacht wurden
  und ob der richtige Ordner rein gepackt wurde.

  * > Abgabe muss die Java Source Dateien enthalten!

  Diese Fehlermeldungen zeigt an, dass die .java Dateien in der JAR nicht enthalten sind. Der Inhalt der JAR lässt sich zum Beispiel mit der Archivverwaltung überpüfen.
  Eventuell ist es hilfreich sich das [Tutorial zu JARs](#{pages_path(:how_to_jar)}) noch einmal anzusehen und zu prüfen, ob alle Schritte richtig befolgt wurden.

  * > Datei ist Fehlerhaft! Struktur Validierung wurde mit Fehler beendet!

  Diese Fehlermeldungen zeigt an, dass etwas sehr schief gelaufen ist. Am besten wäre es die JAR-Datei nochmal neu zu bauen. Ein [Tutorial zu JARs](#{pages_path(:how_to_jar)}) gibt es auf der Hilfeseite von Dozentron. Hier ist Schritt für Schritt erklärt, wie es unter IntelliJ funktioniert.

app/views/java_submission_tester/pages/teacher_help_io.html.slim
h1
  | Here I am walking
' like a !!!

app/views/java_submission_tester/pages/teacher_help_io_junit.html.slim
h1
  | Beispiel für einen Test für IO-Task mit Junit4

pre
  |
    package de.thm.mni;

    import org.junit.Assert;
    import org.junit.Before;
    import org.junit.Test;

    import java.io.IOException;
    import java.nio.file.Files;
    import java.nio.file.Paths;

    public class InputOutputTest {
        private String systemInput;
        private String studentOutput;

        @Before
        public void loadFiles() {
            systemInput = System.getProperty("input");
            studentOutput = System.getProperty("student-output");
        }

        @Test
        public void correctNumber() throws IOException {
            String input = new String(Files.readAllBytes(Paths.get(systemInput)));
            int expectedOutput = input.trim().length();
            int gotOutput;

            gotOutput = Integer.parseInt(new String(Files.readAllBytes(Paths.get(studentOutput))).trim());

            if(expectedOutput > gotOutput)
                Assert.fail("Die gesuchte Zahl ist größer!");
            else if(expectedOutput < gotOutput)
                Assert.fail("Die gesuchte Zahl ist kleiner!");

        }

        @Test
        public void assertFilesSet() {
            Assert.assertNotNull(systemInput);
            Assert.assertNotNull(studentOutput);
        }
    }

app/views/java_submission_tester/pages/teacher_help_submission.html.slim
h1
  | Here I am walking
' like a hurric ane!!!